services:
  tomcat:
    build:
      context: ./docker/tomcat
    hostname: tomcat
    command:
      - run
    ports:
      - "8080:8080"
    volumes:
      - "./docker/tomcat/var/opt/tomcat/:/var/opt/tomcat/"
    environment:
      - LANG=ja_JP.UTF-8
      - CATALINA_BASE=/var/opt/tomcat/example
